add_test(test-CMod-LH-edge "../test.sh")
set_tests_properties(test-CMod-LH-edge PROPERTIES  WORKING_DIRECTORY "00_Genray_Regression_Tests/ci-tests/test-CMod-LH-edge")
add_test(test-CMod-LH-edge-id16 "../test.sh")
set_tests_properties(test-CMod-LH-edge-id16 PROPERTIES  WORKING_DIRECTORY "00_Genray_Regression_Tests/ci-tests/test-CMod-LH-edge-id16")
add_test(EC-ITER-Centra-CD "../test.sh")
set_tests_properties(EC-ITER-Centra-CD PROPERTIES  WORKING_DIRECTORY "00_Genray_Regression_Tests/ci-tests/test-EC-ITER-Centra-CD")
