/*-----------------------------------------------------------------------------
|	gldraw.h
-----------------------------------------------------------------------------*/
extern int main(int argc, char *argv[]);
extern void simulate();
extern void init_events();
extern void transform_view(float *r, float *s, float *t);
extern void spin_draw();
extern void draw_surface();
extern void headertext(long, char);
extern void polygons();
extern void loadvec(long kvert, float *q, float *normp);
extern void set_color(float, float, long);
extern void gethue(float, float *, float *);
extern void updatehist();
extern void arrows();
extern void disks();
extern void draw_disk(float, float, int);
extern void draw_arrow(float, float, int, float, float);
extern void sitelabels();
extern void sim_draw(long,int,float[], float *, float *);
extern void set_filter(char);
extern void test_filter();
extern void init_path();
extern void openfile(int);
extern void init_windows();
extern void init_menus();
extern void redraw_view();
extern void draw_pz(float *,float*,float*);
extern void toggle_hue();
extern void toggle_persp();
extern void enable_rand();
extern void go_sort1();
extern void go_sort();
extern void enable_sort();
extern void ready_sort();
extern void go_reorder();
extern void toggle_cont();
extern void toggle_vector_overlay();
extern void toggle_disks();
extern void toggle_history();
extern void toggle_auto();
extern void toggle_jump(int);
extern void contcolor();
extern void toggle_spin();
extern void toggle_ui();
extern void change_color();
extern void write_postscript();
extern void postscript1(int);
extern void write_state();
extern void read_state();
extern void read_state1(char);
extern void write_state1(char);
extern void run_movie();
extern void restart();
extern void end_of_movie();
extern void reverse_direction();
extern void draw_grid();
extern void comp_set(int);
extern void comp_setk();
extern void freeze();
extern void single_step();
extern void single_step1();
extern void readframe();
extern void readtop();
extern void back1();
extern int back2();
extern void read_sizes();
extern char *read_array(Intt i, char *buf, long *np);
extern long mfe_open(char *fname);
extern void init_arrays(int pass2);
extern int readbuf(Intt fd2, unsigned long *buf, long n);
extern long skiparray(Intt fd1, long n, long off1, unsigned long max1);
extern void swapbytes(char *buf, unsigned int n);
extern void abort1();
extern void printfont();
extern void init_font();
extern void standard_projection();
extern void init_contour();
extern int contour();
extern void cdouble();
extern void chalf();
extern void cvert(float *p0, float *p1, int i, int j, struct XY *xy);
extern void cline(struct XY *xy1, struct XY *xy2);
extern void small_file(int writerec);
